# 配置激活的环境
spring:
  profiles:
    active: hanglian
  http:
    multipart: #文件上传大小限制
      maxFileSize: 1024MB
      maxRequestSize: 10240MB
  jackson: # Jackson配置
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.163.com
    username: kingworld890719@163.com
    password: CyJ890815!
    port: 25

# 服务配置
server:
  port: 8888
  context-path: /payGateway

# 百度服务配置
baidu:
  properties:
    appId: 14279554
    apiKey: 8ouRrPcriKFGzRWbjkIri0RO
    secretKey: lQLF4e0PuOQclrumcjYloc23uGLSsdDr
    imgPath: D://test//cardimg//
