#数据库连接配置
spring:
  datasource:
    name: testdb
    url: jdbc:mysql://10.10.10.134:3306/unionbank15?useUnicode=true&prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: yx123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    minIdle: 1
    initialSize: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'X'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  redis:
    host: 10.10.10.134
    password:
    port: 6379
    database: 3
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

# 日志配置文件
logging:
  config: classpath:logback-spring.xml

pay:
  url:
    notify: ${pay.url.base}/payGateway/payNotice/
    return: ${pay.url.base}/payGateway/payNotice/
    base: https://www.xiaocuitech.com
  time:
    connect: 3000
    read: 15000
    out: 15
  ali:
    appid: 2017122801294605
    mchid: 2088821986613602
    key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCuWD2ivO1hyZmzy9WFJxVF9+UZDA0v2GKs/by3QCD0FelbF4G6oUldiEsM7ZRsEngIIcAd0EQBYCKPaMZXCaQoNF9k82Kk/GSPYTbrFfo55gFawNhjjbMLOMmz8GDtFgLeLBmcdLxu72q1I4AgZYdp3XieEPlRtN7TM5ILnWwkou0eLxJ5beP6VHIhJnoWKxZOnWIBU3Hp3NIZLoh4RiSJ4I25c0bBErYOpJnI8Tcki4bJzYIPFKpUZSMlgY8XuPBONKjGLIq4yS9xHYF8UmfT3t66mYaxUbQ/g0KxZnVeHAXzY2Un+DfVj1Db9c2sYVZ28OTVJC5gbAKnZ+eenxOtAgMBAAECggEAIKWFZSPbj6Qgk/pnUTewVBnHXJlVHtB2Kc6Zt/baNNqlh9kvAbOR+WG8K/+Q+2u57kvjnbGSCm/mCNSlz0aO5rhn5I9uuVZJvk+F6R+Ea7MWLdhOrNWr4T4RBxDMFZk5kEDRyupRHrTWVnT/WRGp+bjvDSpAhXxI/WN6xZIE3hcVENr+yzcVxFoXRxhD5LfNu80bHHYwJn2ZSIUr0gnColw/tzZwmK3ub7fD9xq9j1goV2Nxj8GlJcBAdOUQ4K6r9xwWyXEnU92+0U0Rt7HeJ2IeSMZ/H5TBQSQJG7OrbEnIbiccb3Muo4Tv77a5kQ/cPXrrw78gq8JS6OUPndOIQQKBgQDTjspVy3fgTKZLRkx9n9fywrtKbdZG5AiRICQTHfaqbHMI097O+5OHuDppwXEnGnZH5S98wIdOF+tD67RMKnkC3Vhvgpcn6LZhILs2U/oJvk6rS3TsNADPkWrIu6wC3rlhMX4/hLPRH8qlwzetmUBxHSVkQJvNfrFsWxf9d3KViwKBgQDS+DIC+ZqKnamR+DuNC/FLMInVSl3dUvn5azjC+GZo1was4HHtRrIZW/WgMurFZhVrSywE6AS/NgWXW7seF6XL8YbSro6xz6JFJ8AE94pPigroxtL/1APGhJkY1sFOyQoYvju0r/VWjKPjEpiMuHsRzCDBBnRCnZPl1aiE9gtSpwKBgCpCNJKMsSZhyTnyEedqHXXFhino5MuGU1vB4tLawmHqhdP2lmQcBq0ulKR5WoPoGkZkNmciAiUMTBdmJr6sIT38PuUPXeg/6OZf5mWEwsZdeFNpIDLqdFsB/iWYr1RnbvpGK6S+ejjEs/MGmsGXgjLWEpkC+txCeWhejd04le/fAoGAK5LXwYWMRdUKkPuUUS2GSOFdlpAlkvDwcHOU5bAodr7ywgIZhch0QIid0tixZNQQ2HhOPzUsxdGCliB8JVr9A4J/NkSXdGJOQbpUDrKR/pukZS+rpOtFXFtGw7qXco5TZ4jjDA7LvXSO5PeSSn5P7P0cRsHugVPKmE3o4I1xCUECgYBoATFDaEZvSBMWNfhi4a2Qlkk+O+4axzAecEZoCKxqj8hpVE/1insgEEpCXrZ+nlHcfaAq0eobDM+miCZRwngcan5g6UD5yBMOuyeomhxEeAb3091O7zbtuEAtuPa7QbaJ69ZuoERvNhNVNp6s6nnxftHPRESHiR7npYlpLefmMw==

  wx:
    appid: wx2f3df7a1e61ab90d
    mchid: 1514672641
    key: bjhljf96321478bjhljf96321478bjhl
    secret: 695b719ef08ad9d9636e8e1e48fb27b2
  app:
    appid: wxfc3e964302d9457a
    mchid: 1511181791
    key:  eQcsB2oOtkG1PRdBX0JXKDygUS3AuRKN
    secret: ea4949cb730cf51a08e28399dc0571cf
  path:
    icon: ${pay.path.base}/logo.png
    qrcode: ${pay.path.base}/qrcode/
    base: /payservice

lsb:
  python:
    service:
      url: https://www.xiaocuitech.com/pygroup/api/moledata/operation
      resultUrl: https://www.xiaocuitech.com/pygroup/api/moledata/operationdata
      ak: 698d53ac-cfd1-4ca4-8a44-fd2d50cfc915
  pdf:
    base:
      path: D://pdftest//
  img:
    basePath: D://images//

command:
  hystrix:
    coreSize: 10
    maxQueueSize: 12
    queueSizeRejectionThreshold: 15
    circuitBreakerReuqest: 30
    circuitBreakerErrorPercentage: 40
    circuitBreakerSleepMilliseconds: 3000
    timeout: 500
    fallbackIsolationSemaphoreMaxRequest: 30
    maxRequestBatch: 20
    timerDelayInMilliseconds: 20

baidu:
  properties:
    appId: 14279554
    apiKey: 8ouRrPcriKFGzRWbjkIri0RO
    secretKey: lQLF4e0PuOQclrumcjYloc23uGLSsdDr
    imgPath: /unionbank/service/resources/static/images/