# 配置激活的环境
spring:
  profiles:
    active: develop
  http:
    multipart: #文件上传大小限制
      maxFileSize: 1024MB
      maxRequestSize: 10240MB
  jackson: # Jackson配置
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss

# 服务配置
server:
  port: 80
