#数据库连接配置
spring:
  datasource:
    name: testdb
    url: jdbc:mysql://192.168.188.226:3306/unionbank
    username: root
    password: yx123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    minIdle: 1
    initialSize: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'X'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  redis:
    host: 192.168.188.221
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    database: 12

# 日志配置文件
logging:
  config: classpath:logback-develop.xml

pay:
  url:
    notify: ${pay.url.base}/notify
    return: ${pay.url.base}/return
    base: https://www.szeiv.com
  time:
    connect: 3000
    read: 15000
    out: 15
  ali:
    appid: 2017080308021407
    mchid: 2088721710278241
    key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBDAZx850tjvSGBIpLzn5qrbc4Rpn54suc3AN3QbAxkk88o6Q17ywWZx4qZ8Sh03aR4lF1q37ai8WaqN7YS+QuaCXPpWn/lebc/p7f7L6eTKoI8DSoMqEvcHKugsBNP3iS8nEFRO3ClFN6H7CwZ3yeGX7cu6SFGDgrC2kUlKc93AJ9fAwf+AxGUH1SWsqlrM4HQOA8zA2Mfb/XYw9HrZ6FcP1OMawTdZWzWDHQR+uFnAFKqRoBAhCuigy0XJyHJsg9D6O+9bzjaFHsml1ob1wFeZ9u/Uwb7pJxRY8nXDhSs3btpMAH4hgXZKxvJHMRX++ZeYPDu9W1Q9+NeAFOxZNxAgMBAAECggEAf2OWjTC2rX2cZxveRZ0vcDHSV4xifapj45HRHg3LV/QdojfMZ62VsPvUbHoJQtKUDskCLw2/aRBnXhhr+8tXEnSfNs8Mx1B8GRaFUXnMZko55B7zbEKmmUUBAMJ0AQ2yAiWwako0B0wS59CWxF00SIHUmSPm8bgJ4nweHEHuooHBJaqTFEAkJNKOjdxbTtkeyDP1Q7cwGRNEgN2HvZ654ld/Gcwfi9d9Cv9T2fiOm594CogLMmiyTsP/h32M5SQTclSFzU+FwYrWQ4RRDG1tJMMAtBISxlqcCEhsEBPHBQBtXFJjbpqYPDwfzvgJ2yeRk+FnsoWzkdnWm49XDGcKkQKBgQC8NiOIOtCaZy1AtNoFsC+ibzfM5ATyaMfGUbbBMqI6GaUV5pMG3gHKcaqdTboAzqFAjsi3nPChsP+nd2hCgVqnGCpEhek6rwON6XLgAEcXhmFdxv7flpEy1FpmIN097plBlerGxlaB4qzdoGmxNTCMpfdo4FZxpRSTbMCV/0lBhQKBgQCvhq3af9ZiLZ5btj4h4Ijngw1nGDqZvlypicfDrzx4JIRb7R37Lu1SnNvAVz88qQDCzrAZCKAjE7DbS0xk3r3aqPAumn5N+b+DU0suFtepHnesp2zHNNp/RwyckpZcG1W1ctM/iGxn7uAAz+jJP0JvzUaFke9hSYM4XmgiPK93/QKBgGQh3YeV2vO6nt3FGhVapg0iZKqSSXt6eYauZK+ms557lFPxhxlpNcSx8pacCrBxPmMtU+Y0DeXIWEuNgJ+ZWFR7y8kHAY2iHR78K4y3ORtv+A8/Vsw3u+oyBiI9q9dOQKUfEHhOfym9IkELHhAUf07k4Zsfd34g2LCSdGeZGS1NAoGBAKHEjhYCG6MASCJeI4U1WveDYKbTPa7UMrJNuT4wEprnjNTsA+Wrqi2pQx5RSoate3YO510rBetOCoERNKcCYhdT+4f3+tACjO6LpY4knz3ORp1o8Gfn3jfPU2A5+TmKN8Oyv96d7Msc7HXTJ8fR9Xj0xzny9ZvEFJuu5monY9BBAoGAR+VrIBvFLUYoPqVxBPIHm0o/4kaGQsyNh0xFj+sLgPzXjyE5vER2wFHXRYp120RpgfpBRNvp457aTMsZoWmmnaWYYmS3NEVwXU+ucthJLmWiWvhCDaYaCfJZ/hv3B9goFPb85z+VvsFsMETD8mGEm1suctQmSvtQNuTKT7Uk4LE=
  wx:
    appid: wx19ed09bdae3a4858
    mchid: 1487017392
    key: 7b304f3e0cad637538231b1d69bb7b8d
    secret: 9f7615f750a413d10134fc5041accd57
  path:
    icon: ${pay.path.base}/logo.png
    qrcode: ${pay.path.base}/qrcode/
    base: /payservice
