@startmindmap
* 信息系统基础知识
** 管理信息系统规划
*** 关键成功因素
*** 战略目标集转化法
*** 企业系统规划法
** 信息化需求的3个层次
*** 战略需求
*** 运作需求
*** 技术需求
** 主流集成模式
*** 面向信息的集成
*** 面向过程的集成
*** 面向服务的集成
** 企业门户4类
*** 企业网站
*** 企业知识门户
*** 企业信息门户
*** 企业应用门户
** ERP企业资源
*** 三流
**** 物流
**** 资金流
**** 信息流
*** 四流
**** 商流
@endmindmap